[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fuzz_runs = 1_000_000
remappings = [
  "forge-std=lib/forge-std/src/",
]



[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "attributes_first"
# multiline_func_header = "all"
quote_style = "double"
number_underscore = "preserve"
override_spacing = true
wrap_comments = true
ignore = []


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
